In [1]:
import numpy as np
import pandas as pd


In [2]:
train=pd.read_csv("..\Dataset\power-laws-forecasting-energy-consumption-training-data.csv",sep=';')
test=pd.read_csv("..\Dataset\power-laws-forecasting-energy-consumption-test-data.csv",sep=';')

print("Train:",train.head())
print()
print("Test :", test.head())

Train:     obs_id  SiteId                  Timestamp  ForecastId         Value
0  4852050      42  2016-10-18T02:45:00+00:00        1087  26397.049623
1  1638923      42  2016-10-18T11:45:00+00:00        1087  42958.364641
2  5748910      42  2016-10-18T20:45:00+00:00        1087  27096.919666
3    38199      42  2016-10-20T10:45:00+00:00        1087  50211.408087
4  1338204      42  2016-10-20T18:45:00+00:00        1087  50503.305105

Test :     obs_id  SiteId                  Timestamp  ForecastId          Value
0   323604     235  2014-01-02T19:00:00+00:00        5004  157265.446409
1  2813181     235  2014-01-02T22:00:00+00:00        5004  155498.418922
2  4006999     235  2014-01-02T22:45:00+00:00        5004  155498.418922
3   106973     235  2014-01-03T00:30:00+00:00        5004  157265.446409
4  6793052     235  2014-01-13T14:15:00+00:00        5005   91885.429363


In [3]:
df = pd.concat([train, test], ignore_index=True)
print("Shape:",df.shape)
df

Shape: (7869006, 5)


obs_id  SiteId                  Timestamp  ForecastId         Value
0        4852050      42  2016-10-18T02:45:00+00:00        1087  26397.049623
1        1638923      42  2016-10-18T11:45:00+00:00        1087  42958.364641
2        5748910      42  2016-10-18T20:45:00+00:00        1087  27096.919666
3          38199      42  2016-10-20T10:45:00+00:00        1087  50211.408087
4        1338204      42  2016-10-20T18:45:00+00:00        1087  50503.305105
...          ...     ...                        ...         ...           ...
7869001   268524     261  2014-03-24T03:00:00+00:00        5487  38545.410018
7869002  3203969     261  2014-03-24T12:30:00+00:00        5487  48937.146780
7869003  7721495     261  2014-03-24T22:00:00+00:00        5487           NaN
7869004  5696668     261  2014-03-24T23:30:00+00:00        5487           NaN
7869005  4671263     261  2014-03-25T01:15:00+00:00        5487           NaN

[7869006 rows x 5 columns]

In [4]:
# df['Timestamp'] = pd.to_datetime(df['Timestamp'])
# df.set_index('Timestamp', inplace=True)
# daily_df = df.resample('D').sum().reset_index()

# # Display the resulting daily data
# print(daily_df)

In [5]:
value_count=df.groupby('SiteId')['Value'].count()
top_10=value_count.sort_values(ascending=False)[:10]
top_10

SiteId
302    268160
261    184713
6      167358
269    151565
271    149262
237    144433
8      137704
235    122592
233    122511
276    122434
Name: Value, dtype: int64

In [6]:
top_10_sites = value_count.sort_values(ascending=False).head(10).index

In [7]:
new_df = df[df['SiteId'].isin(top_10_sites)]
new_df

obs_id  SiteId                  Timestamp  ForecastId         Value
20952    6873441       8  2016-09-12T22:30:00+00:00         296  54967.807121
20953    4704819       8  2016-09-12T23:00:00+00:00         296  50948.253037
20954    4669306       8  2016-09-12T23:45:00+00:00         296  29815.442937
20955    6891541       8  2016-09-13T03:30:00+00:00         296  30017.950700
20956    3175634       8  2016-09-13T06:45:00+00:00         296  37248.377869
...          ...     ...                        ...         ...           ...
7869001   268524     261  2014-03-24T03:00:00+00:00        5487  38545.410018
7869002  3203969     261  2014-03-24T12:30:00+00:00        5487  48937.146780
7869003  7721495     261  2014-03-24T22:00:00+00:00        5487           NaN
7869004  5696668     261  2014-03-24T23:30:00+00:00        5487           NaN
7869005  4671263     261  2014-03-25T01:15:00+00:00        5487           NaN

[1588344 rows x 5 columns]

In [8]:
weather_data=pd.read_csv(r"..\Dataset\power-laws-forecasting-energy-consumption-weather.csv",sep=';')
weather_data

Timestamp  Temperature   Distance  SiteId
0        2017-03-03T19:00:00+00:00         10.6  27.489346      51
1        2017-03-03T19:20:00+00:00         11.0  28.663082      51
2        2017-03-03T20:00:00+00:00          6.3  28.307039      51
3        2017-03-03T21:55:00+00:00         10.0  29.797449      51
4        2017-03-03T23:00:00+00:00          5.4  28.307039      51
...                            ...          ...        ...     ...
3957030  2016-09-11T11:00:00+00:00         25.9  28.307039      51
3957031  2016-09-11T11:20:00+00:00         27.0  27.489346      51
3957032  2016-09-11T12:00:00+00:00         27.1  28.307039      51
3957033  2016-09-11T15:50:00+00:00         28.0  27.489346      51
3957034  2016-09-11T18:00:00+00:00         29.6  29.797449      51

[3957035 rows x 4 columns]

In [9]:
weather_data['SiteId'].unique()

array([51, 50, 56, 57, 20, 21, 19, 22, 25, 26, 29, 28, 27, 30, 55, 52, 24,
       23, 36, 35, 48, 47, 38, 37, 49, 33, 34, 46, 32, 42, 44, 39, 45, 40,
       41,  5,  4,  3,  2,  6,  9,  8,  7, 12, 16, 17, 18, 10, 13])

In [10]:
# Merge the DataFrames
merged_df = pd.merge(df, weather_data, on=['SiteId', 'Timestamp'], how='inner')
merged_df

obs_id  SiteId                  Timestamp  ForecastId         Value  \
0       2512063      40  2017-01-11T04:30:00+00:00        1013  10879.083336   
1       2512063      40  2017-01-11T04:30:00+00:00        1013  10879.083336   
2       1148116      40  2017-01-14T20:30:00+00:00        1013   4001.425865   
3       1148116      40  2017-01-14T20:30:00+00:00        1013   4001.425865   
4       7587273      40  2017-01-15T14:30:00+00:00        1013  10088.216946   
...         ...     ...                        ...         ...           ...   
502210  7662083      19  2015-10-21T15:00:00+00:00         571   9207.314048   
502211  7118695      19  2015-10-22T05:30:00+00:00         571   4603.657024   
502212  5854448      19  2015-10-22T07:30:00+00:00         571  26087.389803   
502213  6325226      19  2015-10-22T09:30:00+00:00         571  24552.837461   
502214  4647835      19  2015-10-22T14:00:00+00:00         571  24552.837461   

        Temperature   Distance  
0              -4.0  26.095513  
1              -1.0  24.788361  
2              -2.0  24.788361  
3              -3.0  26.095513  
4               2.0  24.788361  
...             ...        ...  
502210         22.0  19.388165  
502211          9.0  19.388165  
502212          8.0  19.388165  
502213          8.0  19.388165  
502214         13.0  19.388165  

[502215 rows x 7 columns]

In [11]:
merged_df['SiteId'].unique()

array([40,  8,  9, 25, 26, 46, 48, 49, 50, 51, 10, 12, 23, 44, 19,  6,  7,
       16,  2,  3,  5, 20, 33, 29, 32, 38, 22, 41, 13])

In [12]:
Holiday_data = pd.read_csv("..\Dataset\power-laws-forecasting-energy-consumption-holidays.csv", delimiter=';')
Holiday_data

Date                       Holiday  SiteId
0     2016-02-15         Washington's Birthday       1
1     2017-05-29                  Memorial Day       1
2     2017-11-23              Thanksgiving Day       1
3     2017-12-29           New Years Eve Shift       1
4     2017-12-31                 New Years Eve       1
...          ...                           ...     ...
8382  2015-12-26                    Boxing Day     303
8383  2016-05-01    International Workers' Day     304
8384  2015-04-25                Liberation Day     304
8385  2016-03-28                 Easter Monday     305
8386  2016-08-15  Assumption of Mary to Heaven     305

[8387 rows x 3 columns]

In [13]:
Holiday_data['SiteId'].unique()

array([  1,  12,  13,  14,  15,  16,  17,  18,  20,  21,  22,  23,  25,
        26,  27,  32,  33,  34,  39,  40,  42,  43,  44,  45,  47,  48,
        49,  50,  51,  52,  53,  54,  57,  58,  59,  60,  62,  63,  64,
        65,  66,  67,  68,  72,  74,  75,  77,  78,  83,  85,  86,  87,
        88,  90,  93,  94,  96,  98,  99, 100, 101, 102, 105, 106, 107,
       108, 109, 110, 111, 112, 115, 116, 117, 119, 120, 121, 122, 123,
       124, 125, 126, 127, 128, 129, 130, 131, 132, 134, 135, 139, 140,
       141, 142, 143, 145, 146, 148, 149, 150, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 167, 169, 170, 171,
       172, 173, 174, 176, 178, 180, 181, 182, 184, 185, 186, 189, 190,
       192, 193, 194, 195, 196, 197, 199, 200, 201, 202, 203, 204, 205,
       206, 207, 208, 209, 210, 211, 212, 213, 216, 217, 218, 221, 222,
       223, 224, 226, 227, 228, 229, 230, 231, 237, 238, 239, 241, 243,
       246, 247, 248, 250, 251, 252, 253, 254, 255, 256, 257, 25

In [14]:
# Merge the DataFrames
final_df = pd.merge(merged_df, Holiday_data, on=['SiteId'], how='left')
final_df

obs_id  SiteId                  Timestamp  ForecastId         Value  \
0        2512063      40  2017-01-11T04:30:00+00:00        1013  10879.083336   
1        2512063      40  2017-01-11T04:30:00+00:00        1013  10879.083336   
2        2512063      40  2017-01-11T04:30:00+00:00        1013  10879.083336   
3        2512063      40  2017-01-11T04:30:00+00:00        1013  10879.083336   
4        2512063      40  2017-01-11T04:30:00+00:00        1013  10879.083336   
...          ...     ...                        ...         ...           ...   
6096820  7662083      19  2015-10-21T15:00:00+00:00         571   9207.314048   
6096821  7118695      19  2015-10-22T05:30:00+00:00         571   4603.657024   
6096822  5854448      19  2015-10-22T07:30:00+00:00         571  26087.389803   
6096823  6325226      19  2015-10-22T09:30:00+00:00         571  24552.837461   
6096824  4647835      19  2015-10-22T14:00:00+00:00         571  24552.837461   

         Temperature   Distance        Date         Holiday  
0               -4.0  26.095513  2017-11-01  All Saints Day  
1               -4.0  26.095513  2015-05-25     Whit Monday  
2               -4.0  26.095513  2017-05-01      Labour Day  
3               -4.0  26.095513  2017-07-14    Bastille Day  
4               -4.0  26.095513  2016-01-01        New year  
...              ...        ...         ...             ...  
6096820         22.0  19.388165         NaN             NaN  
6096821          9.0  19.388165         NaN             NaN  
6096822          8.0  19.388165         NaN             NaN  
6096823          8.0  19.388165         NaN             NaN  
6096824         13.0  19.388165         NaN             NaN  

[6096825 rows x 9 columns]

In [15]:
final_df['SiteId'].unique()

array([40,  8,  9, 25, 26, 46, 48, 49, 50, 51, 10, 12, 23, 44, 19,  6,  7,
       16,  2,  3,  5, 20, 33, 29, 32, 38, 22, 41, 13])

In [16]:
final_df=final_df.drop(columns=['obs_id','ForecastId','Distance','Date'])

In [17]:
final_df.isna().sum()

SiteId              0
Timestamp           0
Value           63330
Temperature         0
Holiday        345013
dtype: int64

In [18]:
final_df['Holiday']=final_df['Holiday'].apply(lambda x: 0 if pd.isna(x) else 1)
final_df.head()

SiteId                  Timestamp         Value  Temperature  Holiday
0      40  2017-01-11T04:30:00+00:00  10879.083336         -4.0        1
1      40  2017-01-11T04:30:00+00:00  10879.083336         -4.0        1
2      40  2017-01-11T04:30:00+00:00  10879.083336         -4.0        1
3      40  2017-01-11T04:30:00+00:00  10879.083336         -4.0        1
4      40  2017-01-11T04:30:00+00:00  10879.083336         -4.0        1

In [19]:
final_df['Holiday'].unique()

array([1, 0])

In [20]:
# Save the DataFrame to a CSV file
final_df.to_csv('D:\Data Science\Project Omdena\Main Project\Dataset\Multiple site.csv', index=False)
